import { CSSVariableValue } from './css-variables';

type Alpha = number | `${number}%`;
type RGBValue = `${Alpha} ${Alpha} ${Alpha}` | `${CSSVariableValue}`;

type CSSRGB = `rgb(${Alpha},${Alpha},${Alpha})` | `rgb(${RGBValue})`;
type CSSRGBA = `rgba(${Alpha},${Alpha},${Alpha},${Alpha})` | `rgba(${RGBValue} / ${Alpha})`;

type CSSColorFunction =
  | `color(srgb ${RGBValue})`
  | `color(srgb ${RGBValue} / ${Alpha})`
  | `color(display-p3 ${RGBValue})`
  | `color(display-p3 ${RGBValue} / ${Alpha})`
  | `color(a98-rgb ${RGBValue})`
  | `color(a98-rgb ${RGBValue} / ${Alpha})`
  | `color(prophoto-rgb ${RGBValue})`
  | `color(prophoto-rgb ${RGBValue} / ${Alpha})`
  | `color(rec2020 ${RGBValue})`
  | `color(rec2020 ${RGBValue} / ${Alpha})`
  | `color(xyz ${RGBValue})`
  | `color(xyz ${RGBValue} / ${Alpha})`
  | `color(lab ${Alpha} ${Alpha} ${Alpha})`
  | `color(lab ${Alpha} ${Alpha} ${Alpha} / ${Alpha})`
  | `color(lch ${Alpha} ${Alpha} ${Alpha})`
  | `color(lch ${Alpha} ${Alpha} ${Alpha} / ${Alpha})`
  | `color(oklab ${Alpha} ${Alpha} ${Alpha})`
  | `color(oklab ${Alpha} ${Alpha} ${Alpha} / ${Alpha})`
  | `color(oklch ${Alpha} ${Alpha} ${Alpha})`
  | `color(oklch ${Alpha} ${Alpha} ${Alpha} / ${Alpha})`;

export type CSSColorNames =
  | 'currentColor'
  | 'transparent'
  | CSSRGBA
  | CSSRGB
  | CSSColorFunction
  | `#${string}`
  | 'aliceblue'
  | 'antiquewhite'
  | 'aqua'
  | 'aquamarine'
  | 'azure'
  | 'beige'
  | 'bisque'
  | 'black'
  | 'blanchedalmond'
  | 'blue'
  | 'blueviolet'
  | 'brown'
  | 'burlywood'
  | 'cadetblue'
  | 'chartreuse'
  | 'chocolate'
  | 'coral'
  | 'cornflowerblue'
  | 'cornsilk'
  | 'crimson'
  | 'cyan'
  | 'darkblue'
  | 'darkcyan'
  | 'darkgoldenrod'
  | 'darkgray'
  | 'darkgreen'
  | 'darkgrey'
  | 'darkkhaki'
  | 'darkmagenta'
  | 'darkolivegreen'
  | 'darkorange'
  | 'darkorchid'
  | 'darkred'
  | 'darksalmon'
  | 'darkseagreen'
  | 'darkslateblue'
  | 'darkslategray'
  | 'darkslategrey'
  | 'darkturquoise'
  | 'darkviolet'
  | 'deeppink'
  | 'deepskyblue'
  | 'dimgray'
  | 'dimgrey'
  | 'dodgerblue'
  | 'firebrick'
  | 'floralwhite'
  | 'forestgreen'
  | 'fuchsia'
  | 'gainsboro'
  | 'ghostwhite'
  | 'gold'
  | 'goldenrod'
  | 'gray'
  | 'green'
  | 'greenyellow'
  | 'grey'
  | 'honeydew'
  | 'hotpink'
  | 'indianred'
  | 'indigo'
  | 'ivory'
  | 'khaki'
  | 'lavender'
  | 'lavenderblush'
  | 'lawngreen'
  | 'lemonchiffon'
  | 'lightblue'
  | 'lightcoral'
  | 'lightcyan'
  | 'lightgoldenrodyellow'
  | 'lightgray'
  | 'lightgreen'
  | 'lightgrey'
  | 'lightpink'
  | 'lightsalmon'
  | 'lightseagreen'
  | 'lightskyblue'
  | 'lightslategray'
  | 'lightslategrey'
  | 'lightsteelblue'
  | 'lightyellow'
  | 'lime'
  | 'limegreen'
  | 'linen'
  | 'magenta'
  | 'maroon'
  | 'mediumaquamarine'
  | 'mediumblue'
  | 'mediumorchid'
  | 'mediumpurple'
  | 'mediumseagreen'
  | 'mediumslateblue'
  | 'mediumspringgreen'
  | 'mediumturquoise'
  | 'mediumvioletred'
  | 'midnightblue'
  | 'mintcream'
  | 'mistyrose'
  | 'moccasin'
  | 'navajowhite'
  | 'navy'
  | 'oldlace'
  | 'olive'
  | 'olivedrab'
  | 'orange'
  | 'orangered'
  | 'orchid'
  | 'palegoldenrod'
  | 'palegreen'
  | 'paleturquoise'
  | 'palevioletred'
  | 'papayawhip'
  | 'peachpuff'
  | 'peru'
  | 'pink'
  | 'plum'
  | 'powderblue'
  | 'purple'
  | 'rebeccapurple'
  | 'red'
  | 'rosybrown'
  | 'royalblue'
  | 'saddlebrown'
  | 'salmon'
  | 'sandybrown'
  | 'seagreen'
  | 'seashell'
  | 'sienna'
  | 'silver'
  | 'skyblue'
  | 'slateblue'
  | 'slategray'
  | 'slategrey'
  | 'snow'
  | 'springgreen'
  | 'steelblue'
  | 'tan'
  | 'teal'
  | 'thistle'
  | 'tomato'
  | 'turquoise'
  | 'violet'
  | 'wheat'
  | 'white'
  | 'whitesmoke'
  | 'yellow'
  | 'yellowgreen';
